name: Build setup guides
on:
  pull_request:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      - run: |
          ruby build.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout gha-build
          git add .
          git commit -m "setup guides generated"
          git push origin gha-build
